restorer: fix uninitialized variable
Commit b4441d1bd8a56ed9ec08603e1d4acf5c779fe935 ("restorer.c: rm
unneded struct init") removed this initialization, however, it
now causes the build to fail on Alpine with gcc v15.2.0-r2:

  GEN      criu/pie/parasite-blob.h
criu/pie/restorer.c:1230:39: error: variable 'ts' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
 1230 |                         if (sys_clock_gettime(t->clockid, &ts)) {
      |                                                            ^~
1 error generated.
make[2]: *** [/criu/scripts/nmk/scripts/build.mk:118: criu/pie/restorer.o] Error 1
make[1]: *** [criu/Makefile:59: pie] Error 2
make: *** [Makefile:278: criu] Error 2

Signed-off-by: Radostin Stoyanov <rstoyanov@fedoraproject.org>